use_default_settings: true

server:
  secret_key: "OGE2NGQyMmEtMjZlOS00YTM3LWE1YWYtNDQwNzhjZjM5MjNk"

search:
  safe_search: 0
  formats:
    - html
    - json

botdetection:
  ip_limit:
    link_token: false
